# Always comment on PRs, always create new comments
comment:
  behavior: new
  require_changes: false

# Require a minimum coverage for the codecov/project PR check
coverage:
  status:
    patch: off
    project:
      default:
        target: 100%
        threshold: 1%
      metalsmith-github-profile:
        target: 77%
      metalsmith-link-checker:
        target: 96%
      metalsmith-mermaid:
        target: 96%
      metalsmith-tracer:
        target: 88%
      metalsmith-vega:
        target: 89%
