name: Codecov

on:
  pull_request:
    types:
      - opened
      - synchronize  # HEAD has changed, e.g. a push happened
      - reopened
  push:
    branches:
      - 'main'

jobs:
  codecov-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: formsort/action-check-codecov-config@v1

  # !!! The codecov/project check should be required by GitHub !!!
  # See ../../codecov.yml for the configuration that drives the check
  codecov:
    needs:
      - codecov-lint
    runs-on: ubuntu-latest
    steps:
      # Setup and install
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: 'packages/**/package-lock.json'
      - run: npm ci

      # Run test coverage
      - run: npm run test:junit
      - run: tree .
      - run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov
          exec 5>&1
          for dir in packages/*; do
            OUTPUT=$(./codecov --file "${PWD}/${dir}/coverage/lcov.info" --flags "$(basename "${dir}")" --verbose | tee /dev/fd/5)
            echo "${OUTPUT}" | grep --quiet 'error' && exit 1
          done
