# Requires repo secret: NPM_TOKEN ("automation" access token)

name: Publish npm

on:
  push:
    branches:
      - 'main'

jobs:
  node-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      # actions/checkout@v4
      contents: read
      # `npm publish --provenance`
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci
      - name: npm publish
        # https://github.com/bitwarden/clients/pull/3272
        run: |
          echo 'registry="https://registry.npmjs.org/"' > ./.npmrc
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ./.npmrc
          lerna publish --yes from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
