name: Project CI

on:
  pull_request:
    types:
      - opened
      - synchronize  # HEAD has changed, e.g. a push happened
      - reopened

jobs:
  node-unit:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]
        # Note: npm workspaces requires npm v7+ = Node.js v15+
        node-version: [ lts, 18 ]
    steps:
      # Setup and install
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      # Test the source files
      - run: npm test

  markdown-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - run: docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest --ignore "packages/*/test/fixtures/**/*.md" --disable MD013 -- "**/*.md"

  renovate-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: 'renovate.json5'

  # !!! This check should be required by GitHub !!!
  test-status-check:
    needs:
      - node-unit
      - markdown-lint
      - renovate-lint
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
