name: Project CI

on:
  pull_request:
    types:
      - opened
      - synchronize  # HEAD has changed, e.g. a push happened
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-unit:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]
        # Note: npm workspaces requires npm v7+ = Node.js v15+
        node-version: [ lts, 18 ]
    steps:
      # Fix Puppeteer issues on Ubuntu 23.10+
      # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md#option-1_the-easiest-way
      - if: ${{ matrix.os == 'ubuntu' }}
        run: |
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      # Setup and install
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      # Test the source files
      - run: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  node-build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]
    steps:
      # Setup and install
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci
      # Test building
      - run: npm run build

  node-pack:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Setup and install
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci
      # Test building & packing
      - run: |
          npm run pack:all
          for package in packages/*; do
            echo "=== ${package} ==="
            tar -ztvf "${package}"/*.tgz | grep -E '.js$'
          done

  markdown-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - run: docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest --ignore "packages/*/test/fixtures/**/*.md" --disable MD013 -- "**/*.md"

  renovate-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: 'renovate.json5'

  # !!! This check should be required by GitHub !!!
  test-status-check:
    if: always()
    needs:
      - node-unit
      - node-build
      - node-pack
      - markdown-lint
      - renovate-lint
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
